version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - cashless-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - cashless-network

  cashless-api:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./OpenCashlessApi
    container_name: cashless-api
    links:
      - "service-registry:sr"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/safra-open-cashless
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - service-registry
      - gateway
    networks:
      - cashless-network

  gateway:
    image: openjdk:11
    build:
      context: ./Gateway
    container_name: gateway
    links:
      - "service-registry:sr"
    ports:
      - "8081:8761"
    depends_on:
      - postgres
      - service-registry
    networks:
      - cashless-network

  service-registry:
    image: openjdk:11
    build:
      context: ./ServiceRegistry
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - cashless-network

networks:
  cashless-network:
    driver: bridge